# Site settings
title: Just do it!
header-img: img/home-bg.png
email: jeffreyliu0@gmail.com
copyright_name: jeffliu0
description: > # this means to ignore newlines until "baseurl:"
  Yesterday you said tomorrow!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jeffliu0
learn_profile: jeffliu0
email_username: jeffreyliu0@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
